name: C-Gate to MQTT Bridge
version: "1.0.0"
slug: cgate_mqtt
description: >
  C-Gate to MQTT Bridge for Home Assistant. Connects C-Gate to your MQTT broker and supports Home Assistant discovery.
arch:
  - amd64
  - armv7
  - aarch64
url: "https://github.com/RomaDomor/ha-cgate-mqtt"
map:
  - config:rw
  - share:rw
options:
  cbusip: "cgate-server"
  cbusname: "HOME"
  mqtt: "homeassistant.local:1883"
  mqttusername: "cbus"
  mqttpassword: "Password!"
  enableHassDiscovery: false
  getallonstart: false
  getallnetapp: "254/56"
  getallperiod: 900
  retainreads: true
  messageinterval: 200
  logging: false
schema:
  cbusip: str
  cbusname: str
  mqtt: str
  mqttusername: str
  mqttpassword: str
  enableHassDiscovery: bool
  getallonstart: bool
  getallnetapp: str
  getallperiod: int
  retainreads: bool
  messageinterval: int
  logging: bool
